Update Mopnik section
mopsy-team/dokumentacja pull request #22
Opened 2018-06-05 16:26 UTC by Yaqana

2018-06-05 16:49 UTC, oroko123 requested changes

2018-06-05 16:49 UTC, oroko123 commented on praca/praca.tex
>      \textbf{Mopsim} dotyczących:
dotyczące

2018-06-05 16:49 UTC, oroko123 commented on praca/praca.tex
> +z plików w formacie CSV oraz położenia MOP-ów z pliku w formacie xml. Pliki te muszą spełniać pewne
a nie xlsx

2018-06-05 16:49 UTC, oroko123 commented on praca/praca.tex
> +Liczby miejsca parkingowych są obliczane dla konkretnych odcinków dróg.
miejsc

2018-06-05 16:49 UTC, oroko123 commented on praca/praca.tex
> +przy uruchomieniu programu -- wczytywane są domyślne dane i wyniki metodyk są
"i wyniki metodyk" jakoś brzydko

2018-06-05 16:49 UTC, oroko123 commented on praca/praca.tex
> +programisty tak, aby użytkownik mógł mieć wybór.
"mógł mieć wybór" - dość enigmatyczne

2018-06-05 17:49 UTC, klaudialax requested changes
ok, poza drobnymi błędami

2018-06-05 17:49 UTC, klaudialax commented on praca/praca.tex
> +które w Mopniku są ustawione jako parametry domyślne, które mogą być zmienione
"ale mogą być zmienione" 
może tak? bo dziwnie brzmi "które" dwa razy pod rząd

2018-06-05 17:49 UTC, klaudialax commented on praca/praca.tex
> +  \item Liczba istniejących miejsca parkingowych (suma liczb miejsc
miejsc

2018-06-05 17:49 UTC, klaudialax commented on praca/praca.tex
> +programisty tak, aby użytkownik mógł mieć wybór.
zgadzam się. Ja bym skończyła zdanie na "programisty"

2018-06-05 20:49 UTC, Yaqana commented
Poprawione

2018-06-05 20:53 UTC, klaudialax requested changes
powstały dwie nowe literówki

2018-06-05 20:53 UTC, klaudialax commented on praca/praca.tex
> +  \item Urochomić symulacje przeprowadzane za pomocą systemu
uruchomić

2018-06-05 20:53 UTC, klaudialax commented on praca/praca.tex
>  których liczba miejsc parkingowych nie jest wystarczająca. Realizowane jest to
ustalenie

2018-06-06 10:04 UTC, Yaqana commented
już mam nadzieję że dobrze

2018-06-06 10:05 UTC, klaudialax approved these changes

2018-06-06 10:06 UTC, merged

2018-06-06 10:10 UTC, Yaqana commented
wow jak szybko

2018-06-06 10:11 UTC, oroko123 commented
Praca wre!