some fixes in mopsim section
mopsy-team/dokumentacja pull request #35
Opened 2018-06-15 19:43 UTC by NaczelnyRachmistrz

2018-06-15 19:44 UTC, NaczelnyRachmistrz commented
Z jakiegoś powodu diff jest jakiś duży i brzydki...

2018-06-19 10:06 UTC, klaudialax approved these changes
Mam nadzieję, że nic nie pominęłam przez tego dziwnego diffa.

2018-06-19 10:07 UTC, klaudialax commented
ale chwila, to wygląda tak, jakby cała praca była tam wklejona dwa razy... bo w środku jest nagle bibliografia

2018-06-19 10:09 UTC, klaudialax requested changes
jednak nie approve xD

2018-06-19 17:11 UTC, oroko123 commented on praca/praca.tex
> +By przeprowadzać efektywne symulacje, zachowanie agentów powinno jak najbardziej odpowiadać rzeczywistości. Z poziomu programisty do programu Mopsim można dodać kolejne strategie. W pakiecie \texttt{
what

2018-06-19 17:11 UTC, oroko123 commented on praca/praca.tex
> +  \centering
u mad my friend

2018-06-19 17:12 UTC, oroko123 commented on praca/praca.tex
> +Okazało się, że otrzymane zbiory danych nie były wystarczające do wiarygodnego wyznaczenia rozkładów czasu podróży. Jedną z czynności, które podjęliśmy w celu uzupełnienia tych danych było stworzenie
i think it shouldn't be there

2018-06-19 17:12 UTC, oroko123 requested changes
Completely disgusting
czemu można edytować recenzję kogoś innego? - klax
faktycznie xd

2018-06-20 17:56 UTC, NaczelnyRachmistrz commented on praca/praca.tex
> +By przeprowadzać efektywne symulacje, zachowanie agentów powinno jak najbardziej odpowiadać rzeczywistości. Z poziomu programisty do programu Mopsim można dodać kolejne strategie. W pakiecie \texttt{
co?

2018-06-20 17:58 UTC, oroko123 commented on praca/praca.tex
> +By przeprowadzać efektywne symulacje, zachowanie agentów powinno jak najbardziej odpowiadać rzeczywistości. Z poziomu programisty do programu Mopsim można dodać kolejne strategie. W pakiecie \texttt{
nie no chodzi o podwajanie, my friend

2018-06-20 18:12 UTC, klaudialax approved these changes
:)

2018-06-20 18:14 UTC, oroko123 approved these changes

2018-06-20 18:16 UTC, merged