Changed dictionary numbering. Added some info about Mopsik-API
mopsy-team/dokumentacja pull request #6
Opened 2018-03-07 14:02 UTC by oroko123

2018-03-08 08:42 UTC, NaczelnyRachmistrz commented
Usuń TODO.
Usuń z pierwszego "genererowane..." i z drugiego "opisywanych..."

2018-03-08 08:43 UTC, NaczelnyRachmistrz requested changes
Usuń TODO.
Usuń z pierwszego "genererowane..." i z drugiego "opisywanych..."

2018-03-14 21:29 UTC, klaudialax approved these changes
Ładnie :D

2018-03-14 21:40 UTC, NaczelnyRachmistrz reviewed
"Planowane jest rozszerzenie o zapytanie:" tego nie będzie chyba ostatecznie w dokumentacji bo po prostu to rozszerzenie się w niej znajdzie? Jeśli tak, to warto chyba jakoś zaznaczać fragmenty tekstu, które trzeba jeszcze edytować (TODO xd)

2018-03-14 21:41 UTC, klaudialax commented
tego rozszerzenia prawdopodobnie nie napiszemy, bo nie będziemy mieli odpowiednich danych do takiej predykcji

2018-03-14 21:43 UTC, oroko123 commented
To może zostawmy póki co (bez merdża), a zmienię jak już obgadamy ostatecznie.

2018-03-14 21:45 UTC, NaczelnyRachmistrz commented
To jest sens w ogóle o tym pisać? Albo ew. coś w stylu "planowaliśmy jeszcze, ale...". No bo dużo można by pisać o tym czego byśmy nie zrobili gdybyśmy mieli jakieś dane xd

2018-03-14 21:49 UTC, klaudialax commented
Ja bym to zostawiła, to jest taki najważniejszy feature, którego jednak nie zrobimy. A ja bym chciała już merdża, bo potem będą więcej konfliktów, np. dopisuje coś w słowniczku i teraz jest część jednym stylem, część innym.

2018-03-14 21:51 UTC, NaczelnyRachmistrz commented
moglibyśmy zrobić jakiś ogólny rozdział o innych pomysłach/funkcjonalnościach, których z jakiegoś powodu nie zrealizowaliśmy, dobra na razie merdżuję bo ale zapamiętam ten fragment xd

2018-03-14 21:52 UTC, NaczelnyRachmistrz approved these changes

2018-03-14 21:52 UTC, merged